[project]
name = "universalSuccessorFeatures"
description = "usf"

version = "0.1"
authors = [
    { name = "Andres Bermeo Marinelli", email = "andres.bermeo-marinelli@inria.fr" }
]
dependencies = [ ]

[tool.pytest.ini_options]
testpaths = ["test"]
filterwarnings = [ "ignore::DeprecationWarning" ]
