from .multigoal_dqn.state_goal_output_like_paper import StateGoalPaperDQN
from .multigoal_dqn.state_goal_output_augmented_account4w import StateGoalAugmentedDQN
from .multigoal_dqn.feature_goal_output_like_paper import FeatureGoalPaperDQN
from .multigoal_dqn.feature_goal_output_augmented_account4w import FeatureGoalAugumentedDQN

from .usf.state_goal import StateGoalUSF
from .usf.state_goal_weight import StateGoalWeightUSF
from .usf.feature_goal import FeatureGoalUSF
from .usf.feature_goal_weight import FeatureGoalWeightUSF

