from .multigoal_dqn.state_goal_output_like_paper import StateGoalPaperDQN
from .multigoal_dqn.state_goal_output_augmented_account4w import StateGoalAugmentedDQN
from .multigoal_dqn.feature_goal_output_like_paper import FeatureGoalPaperDQN
from .multigoal_dqn.feature_goal_output_augmented_account4w import FeatureGoalAugmentedDQN

from .usf.state_goal import StateGoalUSF
from .usf.state_goal_weight import StateGoalWeightUSF
from .usf.feature_goal import FeatureGoalUSF
from .usf.feature_goal_weight import FeatureGoalWeightUSF
from .usf.feature_goal_weight_augmented import FeatureGoalWeightAugmentedUSF
from .usf.feature_goal_weight_k import FeatureGoalWeightKUSF
from .usf.state_goal_modified import StateGoalUSFModified
